site_name:        StructDualDynProg.jl
repo_url:         https://github.com/blegat/StructDualDynProg.jl
site_description: Implementation of SDDP (Stochastic Dual Dynamic Programming) using the StructJuMP modeling interface
site_author:      Benoît Legat

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Stopping Criterion: stopcrit.md
  - Quick Start: quickstart.md
  - Tutorial: tutorial.md
